name: python unit test cases

on:
  push:
    branches:
     - master




jobs:
  build:
     runs-on: mac-latest


     steps:
     - name: Install dependencies
       run: pip install -r requirements.txt

     - name: Run unit tests
       run: python -m unittest tests.testcases.py


     - name: Notify on success
       if: success()
       run: echo "Unit tests passed successfully"

     - name: Notify on failure
       if: failure()
       run: echo "Unit tests failed"




